version: '1'

services:
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventory
      - POSTGRES_DB=inventory
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  inventory-app:
    image: inventory
    build: inventory
    container_name: inventory-app
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://inventory-db/inventory'
    ports:
      - '8000:8080'
    restart: always
    depends_on:
      - inventory-db

    entrypoint: ['./wait-for-it.sh', '-t', '120', 'inventory-db:5432', '--', 'java', 'org.springframework.boot.loader.JarLauncher']

volumes:
  pgdata: